version: '3'
networks:
  backend:

services:
  server:
    image: nginx:stable-alpine
    volumes:
      - ./backend:/var/www/my-project
      - ./backend/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: server
    ports:
      - "8088:80"
    depends_on:
      - db
      - php
    networks:
      backend:

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./backend/.docker/Mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appbackend
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_NAME: db
    depends_on:
      - php
    networks:
      backend:


  php:
    build:
      context: ./backend/.docker
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/my-project
    volumes:
      - ./backend:/var/www/my-project
    ports:
      - "9000:9000"
    networks:
      backend: